if: branch !~ ^v\d
language: node_js
node_js: node
matrix:
  include:
  - dist: xenial
    addons:
      chrome: stable
      firefox: latest
    before_install:
    - curl -sSLo chromedriver.zip https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
    - unzip -q -d ~/bin chromedriver.zip
    - curl -sSL https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz | tar zxf - -C ~/bin
    script:
    - npm test
    - SELENIUM_BROWSER=firefox node test
  - os: osx
    osx_image: xcode10.1
    before_script: sudo safaridriver --enable
    script: SELENIUM_BROWSER=safari node test
