language: node_js
node_js: node
matrix:
  include:
  - addons:
      chrome: stable
      firefox: latest
    before_install:
    - curl -sSLo chromedriver.zip https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
    - unzip -q -d ~/bin chromedriver.zip
    - curl -sSL https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz | tar zxf - -C ~/bin
    script:
    - npm test
    - SELENIUM_BROWSER=firefox node test
  - os: osx
    osx_image: xcode9.3
    env: SELENIUM_BROWSER=safari
    before_script: sudo safaridriver --enable
branches:
  except: /^v\d/
